### ISSUE TITLE
Release 0.3.

### ISSUE THREAD

**Issue by ldaley** [ReactiveX/RxJavaReactiveStreams#10]
@benjchristensen 0.2 had a problem that the TCK didn't catch, but the tests with Ratpack did.

Would you mind releasing again for @rkuhn's demos?

The release process might be broken though. It's now a multiproject build and I'm not sure I did it right for @quidryan 's sweet sweet tooling to handle the release stuff.

**Comment by benjchristensen** [comment]
I think the artifact names are going to be odd now, i.e.:
- implementation-0.3.0.jar
- test-util-0.3.0.jar

So I imagine you want the submodules to be something like:
- rxjava-reactive-streams
- rxjava-reactive-streams-test-util

**Comment by ldaley** [comment]
We don't want to publish test util. I'll rename the impl project.

**Comment by benjchristensen** [comment]
The way the Gradle plugin currently works it will publish all submodules as artifacts. I'm not aware of a way to turn off publishing of certain modules ... we'd need to tweak the plugin I imagine to add that capability and we won't achieve that tonight in time to release 0.3 so we may want to remove test-util from the settings.gradle just to release tonight.

Also ... very cool how you conditionally build `examples` if we're on Java 8 ... I'm going to steal that for some other places!

**Comment by ldaley** [comment]
Alright, I'll wrap a flag around the enabling of the other stuff. Doing this now.

**Comment by benjchristensen** [comment]
Once done I'll release

**Comment by ldaley** [comment]
Should be gtg.

**Comment by benjchristensen** [comment]
Trying to build and getting an odd error: 

I’m getting an odd upload failure on this build.

It is trying to upload 1.0.0-RC1-SNAPSHOT despite it knowing the version to be 0.3.0:

```
[RxJavaReactiveStreams-0.x-release] $ /scratch/jenkins/workspace/ReactiveX/RxJavaReactiveStreams/RxJavaReactiveStreams-0.x-release/gradlew -Dscope=minor -Dstage=release clean release -Prelease.scope=minor --stacktrace --refresh-dependencies
Inferred version 0.3.0 for final MINOR change.
Publication mavenNebula not found in project :.
Publication named 'mavenNebula' does not exist for project ':' in task ':artifactoryPublish'.
None of the specified publications matched for project ':' - nothing to publish.

...

:rxjava-reactive-streams:check
:rxjava-reactive-streams:compileExamplesJava UP-TO-DATE
:rxjava-reactive-streams:processExamplesResources UP-TO-DATE
:rxjava-reactive-streams:examplesClasses UP-TO-DATE
:rxjava-reactive-streams:build
:build
:verifyReleaseStatus UP-TO-DATE
:rxjava-reactive-streams:verifyReleaseStatus UP-TO-DATE
:rxjava-reactive-streams:bintrayUpload FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rxjava-reactive-streams:bintrayUpload'.
> Could not create version '1.0.0-RC1-SNAPSHOT': HTTP/1.1 400 Bad Request

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':rxjava-reactive-streams:bintrayUpload'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:289)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:166)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:46)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at org.gradle.launcher.Main.main(Main.java:37)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:55)
Caused by: org.gradle.api.GradleException: Could not create version '1.0.0-RC1-SNAPSHOT': HTTP/1.1 400 Bad Request
    at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure6_closure25_closure29.doCall(BintrayUploadTask.groovy:248)
    at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1142)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1076)
    at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
    at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:434)
    at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:383)
    at groovyx.net.http.HTTPBuilder$request$0.call(Unknown Source)
    at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure6.doCall(BintrayUploadTask.groovy:241)
    at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure6.doCall(BintrayUploadTask.groovy)
    at com.jfrog.bintray.gradle.BintrayUploadTask.bintrayUpload(BintrayUploadTask.groovy:305)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:219)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:533)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:516)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 46 more
```

/cc @quidryan

**Comment by benjchristensen** [comment]
Perhaps we have tripped over the plugin assumptions of a single-module project and that is somehow messing it up?

**Comment by ldaley** [comment]
Yeah, that's it. I'll move everything back to the root until I get a chance to discuss with @quidryan

**Comment by ldaley** [comment]
Done.

**Comment by benjchristensen** [comment]
K, trying again.

**Comment by quidryan** [comment]
The version is inferred only if it's not already set. I see in the [gradle.properties](https://github.com/ReactiveX/RxJavaReactiveStreams/blob/0.x/gradle.properties) a version: version=1.0.0-RC1-SNAPSHOT. Remove this version and you should be fine.

**Comment by benjchristensen** [comment]
@alkemist Released 0.3.0 to Bintray and on its way to Maven Central: https://bintray.com/reactivex/RxJava/RxJavaReactiveStreams/0.3.0/view

**Comment by benjchristensen** [comment]
@quidryan but it works fine and ignores that file when we just have a single src folder. So it seems we should just delete that file?

**Comment by quidryan** [comment]
I guess I didn't look when you had "a single src folder", from what I can sorta see that's how it is now and it was having the issue. Yes, the file can be removed. In a multi-module build, the field won't propagate to the children, but we'll still want a single version calculated for all modules.

**Comment by ldaley** [comment]
@quidryan I want to have internal projects that shouldn't be published. Is there a way to opt out of publishing?

**Comment by quidryan** [comment]
Off the top of my head, you'd add bintrayUpload.enabled=false to the internal projects.

**Comment by ldaley** [comment]
Of course should have thought of that.
